const colors = {
  light: {
    text: "#1E293B",
    tint: "#2563EB",
    background: "#F0F4FF",
    foreground: "#1E293B",
    card: "#FFFFFF",
    cardForeground: "#1E293B",
    primary: "#2563EB",
    primaryForeground: "#FFFFFF",
    secondary: "#EFF6FF",
    secondaryForeground: "#1D4ED8",
    muted: "#F1F5F9",
    mutedForeground: "#64748B",
    accent: "#DBEAFE",
    accentForeground: "#1D4ED8",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E2E8F0",
    input: "#E2E8F0",
  },
  dark: {
    text: "#E2E8F0",
    tint: "#4F8AFF",
    background: "#0D1526",
    foreground: "#E2E8F0",
    card: "#152035",
    cardForeground: "#E2E8F0",
    primary: "#4F8AFF",
    primaryForeground: "#FFFFFF",
    secondary: "#1E3A5F",
    secondaryForeground: "#93C5FD",
    muted: "#1A2F4A",
    mutedForeground: "#6B82A8",
    accent: "#1E3A5F",
    accentForeground: "#93C5FD",
    destructive: "#F87171",
    destructiveForeground: "#FFFFFF",
    border: "#1E3A5F",
    input: "#1A2F4A",
  },
  radius: 12,
};

export default colors;
